-- Minimal sample insert script. The full dataset is generated by python main.py --setup.

INSERT OR REPLACE INTO devices (device_id, device_name, device_category, room_location)
VALUES
    ('DEV001', 'Central AC', 'HVAC', 'Building A - Floor 1'),
    ('DEV005', 'Server Rack', 'IT Equipment', 'Building A - Server Room'),
    ('DEV012', 'EV Charger', 'Charging', 'Building B - Parking');

INSERT INTO energy_readings (
    device_id,
    timestamp,
    power_consumption_kwh,
    voltage,
    current,
    temperature,
    energy_cost,
    status,
    anomaly_flag
)
VALUES
    ('DEV001', '2026-01-01 09:00:00', 4.42, 231.1, 19.12, 27.4, 0.796, 'ON', 0),
    ('DEV005', '2026-01-01 09:00:00', 3.31, 229.6, 14.42, 24.8, 0.596, 'ON', 0),
    ('DEV012', '2026-01-01 21:00:00', 12.88, 232.4, 55.42, 22.1, 3.130, 'ON', 1);
